### ISSUE TITLE
Borders

### ISSUE THREAD

**Issue by giovanierthal** [pst2d/csscontrols#2]
I have a simple control, but the left and bottom borders are not displayed:

`Body.InlineStyle := 'border:1px solid #0060DF;';`

[https://i.imgur.com/n0ugrho.png](url)

**Comment by pst2d** [comment]
Control is based on TCSSShape? Please check latest updated version.

**Comment by giovanierthal** [comment]
With the update it works. Some other problems that I had noticed were solved (it was not possible to move or apply styles at design time).

Thank you very much and congratulations!
